name: Run Python Test With Pytest

on: 
  push: 
    branches: 
      - main
      - test # Execute push on test branch
  pull_request: 
    branches: 
      - main
      - test # Execute pull request on test branch

jobs:
  build-and-test: 
    runs-on: ubuntu-latest # Run on the latest Ubuntu runner | Virtual Environment

    steps: 
      - name: checkout Repository # Step 1: Checkout the repository (Clone)
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12.7' # Set Version
          cache: 'pip' # Enable pip cache to dependencies 'pip'

      - name: Install Dependencies # Step 2: Install Dependencies
        run: |
          python -m pip install --upgrade pip # Upgrade pip to the latest version
          pip install -r requirements.txt # Install dependencies from requirements.txt
          pip install pytest httpx # Install pytest & httpx for the testing

      - name: Run test with pytest # step 3: Run test with pytest
        run: python -m pytest # Run pytest to execute the test in the repository